### ISSUE TITLE
vocab-transit still maintained?

### ISSUE THREAD

**Issue by elf-pavlik** [iand/vocab-transit#4]
@iand do you still work on this vocab? if not maybe someone else would like to step up and maintain it.

@pietercolpaert if you feel interested i would help with sharing such responsibility! i would also feel interested in looking at it in context of https://github.com/OpenTransport/vocabulary

**Comment by elf-pavlik** [comment]
@iand what do you think about adding links in this repo and in the website, and marking it as superseded by LinkedGTFS which @pietercolpaert actively develops?

* http://vocab.gtfs.org
* https://github.com/OpenTransport/linked-gtfs
* http://lov.okfn.org/dataset/lov/vocabs/gtfs

**Comment by iand** [comment]
Yes, happy to do so.

**Comment by iand** [comment]
I have updated the README of this repository and will add a pointer to http://vocab.org/transit/ at some point in the future.

**Comment by elf-pavlik** [comment]
thanks! :+1:
